<?php
/**
 * VP Bakery ( formerly Visual Composer ) Headings Presets
 *
 * @package Uber WPBakery Addons
 * @author WOW Layers
 * @link https://wowlayers.com
 */
$presets = array(
	array(
	  'h1' => 'Selvage kitsch vegan, stumptown tilde |newline| waistcoat pickled keytar mixtape. |newline| Kinfolk neutra lomo, scenester.',
	  'h2' => 'Semiotics freegan vegan pork belly tote |newline| bag cornhole. Quinoa yr tousled, ramps |newline| stumptown listicle drinking.',
	  'content' => '',
	  'alignment' => 'left',
	  'inline' => '',
	  'general_css_editor' => '',
	  'el_class' => '',
	  'h1_html' => 'h2',
	  'h1_font' => '',
	  'h1_line_height' => '42px',
	  'h1_font_weight' => '',
	  'h1_font_weight2' => '900:normal',
	  'h1_font_selector' => 'themefont2',
	  'h1_customfont' => '',
	  'h1_font_size' => '32px',
	  'h1_color' => '',
	  'h1_letterspacing' => '-1px',
	  'h1_underline' => '',
	  'h1_underline_color' => '',
	  'h1_underline_width' => '',
	  'h1_underline_height' => '',
	  'h1_high' => '',
	  'h2_html' => 'h2',
	  'h2_font' => '',
	  'h2_line_height' => '42px',
	  'h2_font_weight' => '',
	  'h2_font_weight2' => '100:normal',
	  'h2_font_selector' => 'themefont2',
	  'h2_customfont' => '',
	  'h2_font_size' => '32px',
	  'h2_color' => '',
	  'h2_letterspacing' => '-1px',
	  'h2_underline' => '',
	  'h2_underline_color' => '',
	  'h2_underline_width' => '',
	  'h2_underline_height' => '',
	  'h2_high' => '',
	  'h2_light' => '',
	  'h2_light_high' => '',
	  'p_font' => '',
	  'p_line_height' => '',
	  'p_font_weight' => '',
	  'p_font_weight2' => '',
	  'p_font_selector' => '',
	  'p_customfont' => '',
      'p_letterspacing'	 => '',
	  'p_font_size' => '',
	  'p_color' => '',
	  'p_alignment' => '',
	  'p_css_editor' => '',
	  'animate' => '',
	  'animation' => '',
	  'animation_duration' => '',
	  'animation_delay' => '',
	  'general_css_editor'=>array(
		'margin_top'=>'',
		'margin_right'=>'',
		'margin_bottom'=>'',
		'margin_left'=>'',	
		'border_top_width'=>'',
		'border_right_width'=>'',
		'border_bottom_width'=>'',
		'border_left_width'=>'',	
		'padding_top'=>'',
		'padding_right'=>'',
		'padding_bottom'=>'',
		'padding_left'=>'',
		'border_color'=>'',
		'border_style'=>'',
		'border_radius'=>'',
		'background_color'=>'',
		'background_style'=>'',
	  ),  
	  'h1_css_editor'=>array(
		'margin_top'=>'',
		'margin_right'=>'',
		'margin_bottom'=>'10px',
		'margin_left'=>'',	
		'border_top_width'=>'',
		'border_right_width'=>'',
		'border_bottom_width'=>'',
		'border_left_width'=>'',	
		'padding_top'=>'',
		'padding_right'=>'',
		'padding_bottom'=>'',
		'padding_left'=>'',
		'border_color'=>'',
		'border_style'=>'',
		'border_radius'=>'',
		'background_color'=>'',
		'background_style'=>'',
	  ),   
	  'h2_css_editor'=>array(
		'margin_top'=>'',
		'margin_right'=>'',
		'margin_bottom'=>'',
		'margin_left'=>'',	
		'border_top_width'=>'',
		'border_right_width'=>'',
		'border_bottom_width'=>'',
		'border_left_width'=>'',	
		'padding_top'=>'',
		'padding_right'=>'',
		'padding_bottom'=>'',
		'padding_left'=>'',
		'border_color'=>'',
		'border_style'=>'',
		'border_radius'=>'',
		'background_color'=>'',
		'background_style'=>'',
	  ),   
	  'p_css_editor'=>array(
		'margin_top'=>'',
		'margin_right'=>'',
		'margin_bottom'=>'',
		'margin_left'=>'',	
		'border_top_width'=>'',
		'border_right_width'=>'',
		'border_bottom_width'=>'',
		'border_left_width'=>'',	
		'padding_top'=>'',
		'padding_right'=>'',
		'padding_bottom'=>'',
		'padding_left'=>'',
		'border_color'=>'',
		'border_style'=>'',
		'border_radius'=>'',
		'background_color'=>'',
		'background_style'=>'',
	  ),  
	),
);