<?php
/**
 * VP Bakery ( formerly Visual Composer ) Headings Presets
 *
 * @package Uber WPBakery Addons
 * @author WOW Layers
 * @link https://wowlayers.com
 */
$presets = array(
	array (
	  'h1' => 'Smile.',
	  'h2' => 'believe!',
	  'content' => '<p><span class="light_heading">and of course check our </span><strong>services</strong>.</p>',
	  'alignment' => 'left',
	  'inline' => '',
	  'general_css_editor' => '',
	  'el_class' => '',
	  'h1_html' => 'h4',
	  'h1_font' => '',
	  'h1_line_height' => '1em',
	  'h1_font_weight' => '700:normal',
	  'h1_font_weight2' => '',
	  'h1_font_selector' => 'themefont',
	  'h1_customfont' => '',
	  'h1_font_size' => '300px',
	  'h1_color' => $tc1,
	  'h1_letterspacing' => '-25px',
	  'h1_underline' => '',
	  'h1_underline_color' => '',
	  'h1_underline_width' => '',
	  'h1_underline_height' => '',
	  'h1_high' => '',
	  'h2_html' => 'h2',
	  'h2_font' => '',
	  'h2_line_height' => '1.2em',
	  'h2_font_weight' => '700:normal',
	  'h2_font_weight2' => '',
	  'h2_font_selector' => 'themefont',
	  'h2_customfont' => '',
	  'h2_font_size' => '120px',
	  'h2_color' => $tc2,
	  'h2_letterspacing' => '-5px',
	  'h2_underline' => '',
	  'h2_underline_color' => '',
	  'h2_underline_width' => '',
	  'h2_underline_height' => '',
	  'h2_high' => '',
	  'h2_light' => '',
	  'h2_light_high' => '',
	  'p_font' => '',
	  'p_line_height' => '1.3em',
	  'p_font_weight' => '300:normal',
	  'p_font_weight2' => '',
	  'p_font_selector' => 'themefont',
	  'p_customfont' => '',
      'p_letterspacing'	 => '-3px',
	  'p_font_size' => '56px',
	  'p_color' => '',
	  'p_alignment' => 'left',
	  'animate' => '',
	  'animation' => '',
	  'animation_duration' => '',
	  'animation_delay' => '',
	  'h1_css_editor'=>array(
		'margin_top'=>'0px',
		'margin_right'=>'0px',
		'margin_bottom'=>'-50px',
		'margin_left'=>'0px',	
		'border_top_width'=>'',
		'border_right_width'=>'',
		'border_bottom_width'=>'',
		'border_left_width'=>'',	
		'padding_top'=>'',
		'padding_right'=>'',
		'padding_bottom'=>'',
		'padding_left'=>'',
		'border_color'=>'',
		'border_style'=>'',
		'border_radius'=>'',
		'background_color'=>'',
		'background_style'=>'',
	  ),   
	  'h2_css_editor'=>array(
		'margin_top'=>'-5px',
		'margin_right'=>'',
		'margin_bottom'=>'',
		'margin_left'=>'',	
		'border_top_width'=>'',
		'border_right_width'=>'',
		'border_bottom_width'=>'',
		'border_left_width'=>'',	
		'padding_top'=>'',
		'padding_right'=>'',
		'padding_bottom'=>'',
		'padding_left'=>'',
		'border_color'=>'',
		'border_style'=>'',
		'border_radius'=>'',
		'background_color'=>'',
		'background_style'=>'',
	  ),   
	  'p_css_editor'=>array(
		'margin_top'=>'50px',
		'margin_right'=>'',
		'margin_bottom'=>'',
		'margin_left'=>'',	
		'border_top_width'=>'',
		'border_right_width'=>'',
		'border_bottom_width'=>'',
		'border_left_width'=>'',	
		'padding_top'=>'',
		'padding_right'=>'',
		'padding_bottom'=>'',
		'padding_left'=>'',
		'border_color'=>'',
		'border_style'=>'',
		'border_radius'=>'',
		'background_color'=>'',
		'background_style'=>'',
	  ),  
	),
);