<?php
/**
 * VP Bakery ( formerly Visual Composer ) Headings Presets
 *
 * @package Uber WPBakery Addons
 * @author WOW Layers
 * @link https://wowlayers.com
 */
$presets = array(
	array(
	  'h1' => 'A COOL FACT FROM MISTER ALBERT',
	  'h2' => 'Failure Will Never Overtake Me If My |newline| Determination To Succeed Is Strong Enough.',
	  'content' => '<p style="text-align: left">Wolf moon affogato humblebrag fap mixtape shabby chic polaroid selfies. Before they sold out squid butcher blog umami.</p>',
	  'alignment' => 'left',
	  'inline' => '',
	  'general_css_editor' => '',
	  'el_class' => '',
	  'h1_html' => 'h4',
	  'h1_font' => '',
	  'h1_line_height' => '',
	  'h1_font_weight' => '300:normal',
	  'h1_font_weight2' => '',
	  'h1_font_selector' => 'themefont',
	  'h1_customfont' => '',
	  'h1_font_size' => '14px',
	  'h1_color' => '',
	  'h1_letterspacing' => '',
	  'h1_underline' => '',
	  'h1_underline_color' => '',
	  'h1_underline_width' => '',
	  'h1_underline_height' => '',
	  'h1_high' => '',
	  'h1_css_editor' => '',
	  'h2_html' => 'h2',
	  'h2_font' => '',
	  'h2_line_height' => '56px',
	  'h2_font_weight' => '700:normal',
	  'h2_font_weight2' => '',
	  'h2_font_selector' => 'themefont',
	  'h2_customfont' => '',
	  'h2_font_size' => '42px',
	  'h2_color' => '',
	  'h2_letterspacing' => '',
	  'h2_underline' => '',
	  'h2_underline_color' => '',
	  'h2_underline_width' => '',
	  'h2_underline_height' => '',
	  'h2_high' => '',
	  'h2_light' => 'Failure Will Never Overtake Me If My;',
	  'h2_light_high' => 'Never;',
	  'h2_css_editor' => '',
	  'p_font' => '',
	  'p_line_height' => '42px',
	  'p_font_weight' => '',
	  'p_font_weight2' => '300:normal',
	  'p_font_selector' => 'themefont2',
	  'p_customfont' => '',
      'p_letterspacing'	 => '',
	  'p_font_size' => '24px',
	  'p_color' => '',
	  'p_alignment' => 'left',
	  'p_css_editor' => '',
	  'animate' => '',
	  'animation' => '',
	  'animation_duration' => '',
	  'animation_delay' => '',
	  'general_css_editor'=>array(
		'margin_top'=>'',
		'margin_right'=>'',
		'margin_bottom'=>'',
		'margin_left'=>'',	
		'border_top_width'=>'',
		'border_right_width'=>'',
		'border_bottom_width'=>'',
		'border_left_width'=>'',	
		'padding_top'=>'',
		'padding_right'=>'',
		'padding_bottom'=>'',
		'padding_left'=>'',
		'border_color'=>'',
		'border_style'=>'',
		'border_radius'=>'',
		'background_color'=>'',
		'background_style'=>'',
	  ),  
	  'h1_css_editor'=>array(
		'margin_top'=>'0px',
		'margin_right'=>'0px',
		'margin_bottom'=>'30px',
		'margin_left'=>'0px',	
		'border_top_width'=>'',
		'border_right_width'=>'',
		'border_bottom_width'=>'',
		'border_left_width'=>'',	
		'padding_top'=>'',
		'padding_right'=>'',
		'padding_bottom'=>'',
		'padding_left'=>'',
		'border_color'=>'',
		'border_style'=>'',
		'border_radius'=>'',
		'background_color'=>'',
		'background_style'=>'',
	  ),   
	  'h2_css_editor'=>array(
		'margin_top'=>'0px',
		'margin_right'=>'',
		'margin_bottom'=>'20px',
		'margin_left'=>'',	
		'border_top_width'=>'',
		'border_right_width'=>'',
		'border_bottom_width'=>'',
		'border_left_width'=>'',	
		'padding_top'=>'',
		'padding_right'=>'',
		'padding_bottom'=>'',
		'padding_left'=>'',
		'border_color'=>'',
		'border_style'=>'',
		'border_radius'=>'',
		'background_color'=>'',
		'background_style'=>'',
	  ),   
	  'p_css_editor'=>array(
		'margin_top'=>'0px',
		'margin_right'=>'0px',
		'margin_bottom'=>'0px',
		'margin_left'=>'0px',	
		'border_top_width'=>'',
		'border_right_width'=>'',
		'border_bottom_width'=>'',
		'border_left_width'=>'',	
		'padding_top'=>'',
		'padding_right'=>'',
		'padding_bottom'=>'',
		'padding_left'=>'',
		'border_color'=>'',
		'border_style'=>'',
		'border_radius'=>'',
		'background_color'=>'',
		'background_style'=>'',
	  ),  
	),
);