<?php
/**
 * VP Bakery ( formerly Visual Composer ) Headings Presets
 *
 * @package Uber WPBakery Addons
 * @author WOW Layers
 * @link https://wowlayers.com
 */
$presets = array(
	array(
	  'h1' => 'ARE YOU READY?',
	  'h2' => 'Pack your bags. Get ready to',
	  'content' => '<p style="text-align:center">EXPLORE THE WORLD<span class="themecolor1">.</span></p>',
	  'alignment' => 'center',
	  'inline' => '',
	  'general_css_editor' => '',
	  'el_class' => '',
	  'h1_html' => 'h4',
	  'h1_font' => '',
	  'h1_line_height' => '1em',
	  'h1_font_weight' => '500:normal',
	  'h1_font_weight2' => '',
	  'h1_font_selector' => 'themefont',
	  'h1_customfont' => '',
	  'h1_font_size' => '14px',
	  'h1_color' => '',
	  'h1_letterspacing' => '',
	  'h1_underline' => '',
	  'h1_underline_color' => '',
	  'h1_underline_width' => '',
	  'h1_underline_height' => '',
	  'h1_high' => '',
	  'h2_html' => 'h2',
	  'h2_font' => '',
	  'h2_line_height' => '1.2em',
	  'h2_font_weight' => '300:normal',
	  'h2_font_weight2' => '',
	  'h2_font_selector' => 'themefont',
	  'h2_customfont' => '',
	  'h2_font_size' => '24px',
	  'h2_color' => 'themecolor1',
	  'h2_letterspacing' => '',
	  'h2_underline' => '',
	  'h2_underline_color' => '',
	  'h2_underline_width' => '',
	  'h2_underline_height' => '',
	  'h2_high' => '',
	  'h2_light' => '',
	  'h2_light_high' => '',
	  'p_font' => '',
	  'p_line_height' => '1em',
	  'p_font_weight' => '700:normal',
	  'p_font_weight2' => '',
	  'p_font_selector' => 'themefont',
	  'p_customfont' => '',
      'p_letterspacing'	 => '-2px',
	  'p_font_size' => '96px',
	  'p_color' => $hc,
	  'p_alignment' => 'center',
	  'animate' => '',
	  'animation' => '',
	  'animation_duration' => '',
	  'animation_delay' => '',
	  'general_css_editor'=>array(
		'margin_top'=>'',
		'margin_right'=>'',
		'margin_bottom'=>'',
		'margin_left'=>'',	
		'border_top_width'=>'',
		'border_right_width'=>'',
		'border_bottom_width'=>'',
		'border_left_width'=>'',	
		'padding_top'=>'',
		'padding_right'=>'',
		'padding_bottom'=>'',
		'padding_left'=>'',
		'border_color'=>'',
		'border_style'=>'',
		'border_radius'=>'',
		'background_color'=>'',
		'background_style'=>'',
	  ),  
	  'h1_css_editor'=>array(
		'margin_top'=>'0px',
		'margin_right'=>'0px',
		'margin_bottom'=>'12px',
		'margin_left'=>'0px',	
		'border_top_width'=>'',
		'border_right_width'=>'',
		'border_bottom_width'=>'',
		'border_left_width'=>'',	
		'padding_top'=>'5px',
		'padding_right'=>'5px',
		'padding_bottom'=>'5px',
		'padding_left'=>'5px',
		'border_color'=>'',
		'border_style'=>'',
		'border_radius'=>'',
		'background_color'=>'#ffea00',
		'background_style'=>'',
	  ),   
	  'h2_css_editor'=>array(
		'margin_top'=>'0px',
		'margin_right'=>'',
		'margin_bottom'=>'10px',
		'margin_left'=>'',	
		'border_top_width'=>'',
		'border_right_width'=>'',
		'border_bottom_width'=>'',
		'border_left_width'=>'',	
		'padding_top'=>'',
		'padding_right'=>'',
		'padding_bottom'=>'',
		'padding_left'=>'',
		'border_color'=>'',
		'border_style'=>'',
		'border_radius'=>'',
		'background_color'=>'',
		'background_style'=>'',
	  ),   
	  'p_css_editor'=>array(
		'margin_top'=>'0px',
		'margin_right'=>'0px',
		'margin_bottom'=>'0px',
		'margin_left'=>'0px',	
		'border_top_width'=>'',
		'border_right_width'=>'',
		'border_bottom_width'=>'',
		'border_left_width'=>'',	
		'padding_top'=>'',
		'padding_right'=>'',
		'padding_bottom'=>'',
		'padding_left'=>'',
		'border_color'=>'',
		'border_style'=>'',
		'border_radius'=>'',
		'background_color'=>'',
		'background_style'=>'',
	  ),  
	),
);