<?php
/**
 * VP Bakery ( formerly Visual Composer ) Headings Presets
 *
 * @package Uber WPBakery Addons
 * @author WOW Layers
 * @link https://wowlayers.com
 */
$presets = array(
	array(
	  'h1' => 'Have a look at some',
	  'h2' => 'Some fresh screenshots',
	  'content'=>'<p style="text-align:center">Viral marfa banh mi crucifix, ennui gastropub bespoke <br> cray tofu stumptown celiac pinterest tote bag.</p>',
	  'alignment' => 'center',
	  'inline' => '',
	  'el_class' => '',
	  'h1_html' => 'h4',
	  'h1_font' => '',
	  'h1_line_height' => '1.4em',
	  'h1_font_weight' => '100:normal',
	  'h1_font_weight2' => '',
	  'h1_font_selector' => 'themefont',
	  'h1_customfont' => '',
	  'h1_font_size' => '24px',
	  'h1_color' => '#FFFFFF',
	  'h1_letterspacing' => '',
	  'h1_underline' => '',
	  'h1_underline_color' => '',
	  'h1_underline_width' => '',
	  'h1_underline_height' => '',
	  'h1_high' => '',
	  'h2_html' => 'h2',
	  'h2_font' => '',
	  'h2_line_height' => '56px',
	  'h2_font_weight' => '400:normal',
	  'h2_font_weight2' => '',
	  'h2_font_selector' => 'themefont',
	  'h2_customfont' => '',
	  'h2_font_size' => '42px',
	  'h2_color' => '#FFFFFF',
	  'h2_letterspacing' => '-3px',
	  'h2_underline' => 'yes',
	  'h2_underline_color' => '',
	  'h2_underline_width' => '',
	  'h2_underline_height' => '2px',
	  'h2_high' => 'fresh;',
	  'h2_light' => '',
	  'h2_light_high' => '',
	  'p_font' => '',
	  'p_line_height' => '32px',
	  'p_font_weight' => '300:normal',
	  'p_font_weight2' => '',
	  'p_font_selector' => 'themefont',
	  'p_customfont' => '',
      'p_letterspacing'	 => '',
	  'p_font_size' => '18px',
	  'p_color' => '#636a82',
	  'p_alignment' => 'center',
	  'animate' => '',
	  'animation' => '',
	  'animation_duration' => '',
	  'animation_delay' => '',
	  'general_css_editor'=>array(
		'margin_top'=>'',
		'margin_right'=>'',
		'margin_bottom'=>'',
		'margin_left'=>'',	
		'border_top_width'=>'',
		'border_right_width'=>'',
		'border_bottom_width'=>'',
		'border_left_width'=>'',	
		'padding_top'=>'',
		'padding_right'=>'',
		'padding_bottom'=>'',
		'padding_left'=>'',
		'border_color'=>'',
		'border_style'=>'',
		'border_radius'=>'',
		'background_color'=>'',
		'background_style'=>'',
	  ),  
	  'h1_css_editor'=>array(
		'margin_top'=>'0px',
		'margin_right'=>'0px',
		'margin_bottom'=>'0px',
		'margin_left'=>'0px',	
		'border_top_width'=>'',
		'border_right_width'=>'',
		'border_bottom_width'=>'',
		'border_left_width'=>'',	
		'padding_top'=>'',
		'padding_right'=>'',
		'padding_bottom'=>'',
		'padding_left'=>'',
		'border_color'=>'',
		'border_style'=>'',
		'border_radius'=>'',
		'background_color'=>'',
		'background_style'=>'',
	  ),   
	  'h2_css_editor'=>array(
		'margin_top'=>'-5px',
		'margin_right'=>'',
		'margin_bottom'=>'25px',
		'margin_left'=>'',	
		'border_top_width'=>'',
		'border_right_width'=>'',
		'border_bottom_width'=>'',
		'border_left_width'=>'',	
		'padding_top'=>'',
		'padding_right'=>'',
		'padding_bottom'=>'',
		'padding_left'=>'',
		'border_color'=>'',
		'border_style'=>'',
		'border_radius'=>'',
		'background_color'=>'',
		'background_style'=>'',
	  ),   
	  'p_css_editor'=>array(
		'margin_top'=>'-5px',
		'margin_right'=>'0px',
		'margin_bottom'=>'0px',
		'margin_left'=>'0px',	
		'border_top_width'=>'',
		'border_right_width'=>'',
		'border_bottom_width'=>'',
		'border_left_width'=>'',	
		'padding_top'=>'',
		'padding_right'=>'',
		'padding_bottom'=>'',
		'padding_left'=>'',
		'border_color'=>'',
		'border_style'=>'',
		'border_radius'=>'',
		'background_color'=>'',
		'background_style'=>'',
	  ),  
	),
);