<?php
/**
 * VP Bakery ( formerly Visual Composer ) Headings Presets
 *
 * @package Uber WPBakery Addons
 * @author WOW Layers
 * @link https://wowlayers.com
 */
$presets = array(
	array(
	  'h1' => '',
	  'h2' => 'Join over 20 milions |newline| users and get your Infinito |newline| App copy today!',
	  'content'=>'',
	  'alignment' => 'left',
	  'inline' => '',
	  'el_class' => '',
	  'h1_html' => 'h4',
	  'h1_font' => '',
	  'h1_line_height' => '',
	  'h1_font_weight' => '',
	  'h1_font_weight2' => '',
	  'h1_font_selector' => '',
	  'h1_customfont' => '',
	  'h1_font_size' => '',
	  'h1_color' => '',
	  'h1_letterspacing' => '',
	  'h1_underline' => '',
	  'h1_underline_color' => '',
	  'h1_underline_width' => '',
	  'h1_underline_height' => '',
	  'h1_high' => '',
	  'h2_html' => 'h2',
	  'h2_font' => '',
	  'h2_line_height' => '80px',
	  'h2_font_weight' => '100:normal',
	  'h2_font_weight2' => '',
	  'h2_font_selector' => 'themefont',
	  'h2_customfont' => '',
	  'h2_font_size' => '72px',
	  'h2_color' => '',
	  'h2_letterspacing' => '-3px',
	  'h2_underline' => 'yes',
	  'h2_underline_color' => '#1c2133',
	  'h2_underline_width' => '',
	  'h2_underline_height' => '2px',
	  'h2_high' => '',
	  'h2_light' => '',
	  'h2_light_high' => '',
	  'p_font' => '',
	  'p_line_height' => '',
	  'p_font_weight' => '',
	  'p_font_weight2' => '',
	  'p_font_selector' => '',
	  'p_customfont' => '',
      'p_letterspacing'	 => '',
	  'p_font_size' => '',
	  'p_color' => '',
	  'p_alignment' => '',
	  'animate' => '',
	  'animation' => '',
	  'animation_duration' => '',
	  'animation_delay' => '',
	  'general_css_editor'=>array(
		'margin_top'=>'',
		'margin_right'=>'',
		'margin_bottom'=>'',
		'margin_left'=>'',	
		'border_top_width'=>'',
		'border_right_width'=>'',
		'border_bottom_width'=>'',
		'border_left_width'=>'',	
		'padding_top'=>'',
		'padding_right'=>'',
		'padding_bottom'=>'',
		'padding_left'=>'',
		'border_color'=>'',
		'border_style'=>'',
		'border_radius'=>'',
		'background_color'=>'',
		'background_style'=>'',
	  ),  
	  'h1_css_editor'=>array(
		'margin_top'=>'',
		'margin_right'=>'',
		'margin_bottom'=>'',
		'margin_left'=>'',	
		'border_top_width'=>'',
		'border_right_width'=>'',
		'border_bottom_width'=>'',
		'border_left_width'=>'',	
		'padding_top'=>'',
		'padding_right'=>'',
		'padding_bottom'=>'',
		'padding_left'=>'',
		'border_color'=>'',
		'border_style'=>'',
		'border_radius'=>'',
		'background_color'=>'',
		'background_style'=>'',
	  ),   
	  'h2_css_editor'=>array(
		'margin_top'=>'',
		'margin_right'=>'',
		'margin_bottom'=>'50px',
		'margin_left'=>'',	
		'border_top_width'=>'',
		'border_right_width'=>'',
		'border_bottom_width'=>'',
		'border_left_width'=>'',	
		'padding_top'=>'',
		'padding_right'=>'',
		'padding_bottom'=>'',
		'padding_left'=>'',
		'border_color'=>'',
		'border_style'=>'',
		'border_radius'=>'',
		'background_color'=>'',
		'background_style'=>'',
	  ),   
	  'p_css_editor'=>array(
		'margin_top'=>'',
		'margin_right'=>'',
		'margin_bottom'=>'',
		'margin_left'=>'',	
		'border_top_width'=>'',
		'border_right_width'=>'',
		'border_bottom_width'=>'',
		'border_left_width'=>'',	
		'padding_top'=>'',
		'padding_right'=>'',
		'padding_bottom'=>'',
		'padding_left'=>'',
		'border_color'=>'',
		'border_style'=>'',
		'border_radius'=>'',
		'background_color'=>'',
		'background_style'=>'',
	  ),  
	),
);